### ISSUE TITLE
Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by PuAlbert** [Inqnuam/esbuild-plugin-handlebars#3]
if template includes nested injected function , it would not compile helpers function into code 
and I fork a new repo to fix this issue
[https://www.npmjs.com/package/esbuild-handlebars](https://www.npmjs.com/package/esbuild-handlebars)

**Comment by Inqnuam** [comment]
Hello, thanks for reporting.
Please open a Pull request if you want it to be merged in this package
